### ISSUE TITLE
lib/key.dart : No such file or directory

### ISSUE THREAD

**Issue by makorne** [Blakexx/CryptoTracker#4]
```
lib/main.dart:18:8: Error: Error when reading 'lib/key.dart': No such file or directory
import "key.dart";                                                      
       ^                                                                
lib/main.dart:81:37: Error: Getter not found: 'syncKey'.                
  SyncfusionLicense.registerLicense(syncKey);    
```

**Comment by Blakexx** [comment]
Create a file `lib/key.dart` with contents:
`String syncKey = "";`

**Comment by makorne** [comment]
Sorry there is another error:

```
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.18.0/lib/src/picture_provider.dart:50:59: Error: No named parameter with the name 'nullOk'.
        context != null ? Localizations.localeOf(context, nullOk: true) : null,
                                                          ^^^^^^
../../../snap/flutter/common/flutter/packages/flutter/lib/src/widgets/localizations.dart:413:17: Context: Found this candidate, but the arguments don't match.
  static Locale localeOf(BuildContext context) {
                ^^^^^^^^
Failed to compile application.
```
Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f4abaa0735 (6 weeks ago) • 2021-07-01 12:46:11 -0700
Engine • revision 241c87ad80
Tools • Dart 2.13.4
Linux fedora 5.13.8-200.fc34.x86_64 #1 SMP Wed Aug 4 19:59:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Blakexx** [comment]
No need to apologize, this error is my fault. I wrote this code a while ago and and set the dependencies to auto-upgrade. What I think has happened is the pub dependencies have upgraded to a point that no longer works with my old code. I will need to go and find what versions this worked with and add them to `pubspec.yaml`.

**Comment by Blakexx** [comment]
I have made [a commit](https://github.com/Blakexx/CryptoTracker/commit/80cbaeb3a29371bb7ca12244d5a9c1e82c0bec48) which should fix this issue. Let me know what happens.

**Comment by adamsyy** [comment]
is this issue fixed? if not can I work on it

**Comment by Blakexx** [comment]
It should be fixed.

**Comment by adamsyy** [comment]
oh okay. is there anything i can work on this project? i am new to open source and would love to contribute
